<?php

declare(strict_types=1);

namespace App\Model;

use JsonException;

final class SardinianLocation
{
    /** @var array<string, list<string>>|null */
    private static ?array $locations = null;

    /** @var array<string, array<string, string>>|null */
    private static ?array $postalCodes = null;

    /** @return array<string, list<string>> */
    public static function all(): array
    {
        if (self::$locations !== null) {
            return self::$locations;
        }

        try {
            $locations = json_decode(<<<'JSON'
{
    "Città metropolitana di Cagliari": [
        "Armungia",
        "Assemini",
        "Ballao",
        "Barrali",
        "Burcei",
        "Cagliari",
        "Capoterra",
        "Castiadas",
        "Decimomannu",
        "Decimoputzu",
        "Dolianova",
        "Domus de Maria",
        "Donori",
        "Elmas",
        "Escalaplano",
        "Escolca",
        "Esterzili",
        "Genoni",
        "Gergei",
        "Gesico",
        "Goni",
        "Guamaggiore",
        "Guasila",
        "Isili",
        "Mandas",
        "Maracalagonis",
        "Monastir",
        "Monserrato",
        "Muravera",
        "Nuragus",
        "Nurallao",
        "Nuraminis",
        "Nurri",
        "Orroli",
        "Ortacesus",
        "Pimentel",
        "Pula",
        "Quartucciu",
        "Quartu Sant'Elena",
        "Sadali",
        "Samatzai",
        "San Basilio",
        "San Nicolò Gerrei",
        "San Sperate",
        "Sant'Andrea Frius",
        "San Vito",
        "Sarroch",
        "Selargius",
        "Selegas",
        "Senorbì",
        "Serdiana",
        "Serri",
        "Sestu",
        "Settimo San Pietro",
        "Siliqua",
        "Silius",
        "Sinnai",
        "Siurgus Donigala",
        "Soleminis",
        "Suelli",
        "Ussana",
        "Uta",
        "Vallermosa",
        "Villanova Tulo",
        "Villaputzu",
        "Villasalto",
        "Villa San Pietro",
        "Villasimius",
        "Villasor",
        "Villaspeciosa"
    ],
    "Città metropolitana di Sassari": [
        "Alghero",
        "Anela",
        "Ardara",
        "Banari",
        "Benetutti",
        "Bessude",
        "Bonnanaro",
        "Bono",
        "Bonorva",
        "Borutta",
        "Bottidda",
        "Bultei",
        "Bulzi",
        "Burgos",
        "Cargeghe",
        "Castelsardo",
        "Cheremule",
        "Chiaramonti",
        "Codrongianos",
        "Cossoine",
        "Erula",
        "Esporlatu",
        "Florinas",
        "Giave",
        "Illorai",
        "Ittireddu",
        "Ittiri",
        "Laerru",
        "Mara",
        "Martis",
        "Monteleone Rocca Doria",
        "Mores",
        "Muros",
        "Nughedu San Nicolò",
        "Nule",
        "Nulvi",
        "Olmedo",
        "Osilo",
        "Ossi",
        "Ozieri",
        "Padria",
        "Pattada",
        "Perfugas",
        "Ploaghe",
        "Porto Torres",
        "Pozzomaggiore",
        "Putifigari",
        "Romana",
        "Santa Maria Coghinas",
        "Sassari",
        "Sedini",
        "Semestene",
        "Sennori",
        "Siligo",
        "Sorso",
        "Stintino",
        "Tergu",
        "Thiesi",
        "Tissi",
        "Torralba",
        "Tula",
        "Uri",
        "Usini",
        "Valledoria",
        "Viddalba",
        "Villanova Monteleone"
    ],
    "Provincia dell'Ogliastra": [
        "Arzana",
        "Bari Sardo",
        "Baunei",
        "Cardedu",
        "Elini",
        "Gairo",
        "Girasole",
        "Ilbono",
        "Jerzu",
        "Lanusei",
        "Loceri",
        "Lotzorai",
        "Osini",
        "Perdasdefogu",
        "Seui",
        "Talana",
        "Tertenia",
        "Tortolì",
        "Triei",
        "Ulassai",
        "Urzulei",
        "Ussassai",
        "Villagrande Strisaili"
    ],
    "Provincia della Gallura Nord-Est Sardegna": [
        "Aggius",
        "Aglientu",
        "Alà dei Sardi",
        "Arzachena",
        "Badesi",
        "Berchidda",
        "Bortigiadas",
        "Buddusò",
        "Budoni",
        "Calangianus",
        "Golfo Aranci",
        "La Maddalena",
        "Loiri Porto San Paolo",
        "Luogosanto",
        "Luras",
        "Monti",
        "Olbia",
        "Oschiri",
        "Padru",
        "Palau",
        "Sant'Antonio di Gallura",
        "Santa Teresa Gallura",
        "San Teodoro",
        "Telti",
        "Tempio Pausania",
        "Trinità d'Agultu e Vignola"
    ],
    "Provincia del Medio Campidano": [
        "Arbus",
        "Barumini",
        "Collinas",
        "Furtei",
        "Genuri",
        "Gesturi",
        "Gonnosfanadiga",
        "Guspini",
        "Las Plassas",
        "Lunamatrona",
        "Pabillonis",
        "Pauli Arbarei",
        "Samassi",
        "San Gavino Monreale",
        "Sanluri",
        "Sardara",
        "Segariu",
        "Serramanna",
        "Serrenti",
        "Setzu",
        "Siddi",
        "Tuili",
        "Turri",
        "Ussaramanna",
        "Villacidro",
        "Villamar",
        "Villanovaforru",
        "Villanovafranca"
    ],
    "Provincia del Sulcis Iglesiente": [
        "Buggerru",
        "Calasetta",
        "Carbonia",
        "Carloforte",
        "Domusnovas",
        "Fluminimaggiore",
        "Giba",
        "Gonnesa",
        "Iglesias",
        "Masainas",
        "Musei",
        "Narcao",
        "Nuxis",
        "Perdaxius",
        "Piscinas",
        "Portoscuso",
        "San Giovanni Suergiu",
        "Sant'Anna Arresi",
        "Sant'Antioco",
        "Santadi",
        "Teulada",
        "Tratalias",
        "Villamassargia",
        "Villaperuccio"
    ],
    "Provincia di Nuoro": [
        "Aritzo",
        "Atzara",
        "Austis",
        "Belvì",
        "Birori",
        "Bitti",
        "Bolotana",
        "Borore",
        "Bortigali",
        "Desulo",
        "Dorgali",
        "Dualchi",
        "Fonni",
        "Gadoni",
        "Galtellì",
        "Gavoi",
        "Irgoli",
        "Lei",
        "Loculi",
        "Lodine",
        "Lodè",
        "Lula",
        "Macomer",
        "Mamoiada",
        "Meana Sardo",
        "Noragugume",
        "Nuoro",
        "Oliena",
        "Ollolai",
        "Olzai",
        "Onanì",
        "Onifai",
        "Oniferi",
        "Orani",
        "Orgosolo",
        "Orosei",
        "Orotelli",
        "Ortueri",
        "Orune",
        "Osidda",
        "Ottana",
        "Ovodda",
        "Posada",
        "Sarule",
        "Seulo",
        "Silanus",
        "Sindia",
        "Siniscola",
        "Sorgono",
        "Teti",
        "Tiana",
        "Tonara",
        "Torpè"
    ],
    "Provincia di Oristano": [
        "Abbasanta",
        "Aidomaggiore",
        "Albagiara",
        "Ales",
        "Allai",
        "Arborea",
        "Ardauli",
        "Assolo",
        "Asuni",
        "Baradili",
        "Baratili San Pietro",
        "Baressa",
        "Bauladu",
        "Bidonì",
        "Bonarcado",
        "Boroneddu",
        "Bosa",
        "Busachi",
        "Cabras",
        "Cuglieri",
        "Curcuris",
        "Flussio",
        "Fordongianus",
        "Ghilarza",
        "Gonnoscodina",
        "Gonnosnò",
        "Gonnostramatza",
        "Laconi",
        "Magomadas",
        "Marrubiu",
        "Masullas",
        "Milis",
        "Modolo",
        "Mogorella",
        "Mogoro",
        "Montresta",
        "Morgongiori",
        "Narbolia",
        "Neoneli",
        "Norbello",
        "Nughedu Santa Vittoria",
        "Nurachi",
        "Nureci",
        "Ollastra",
        "Oristano",
        "Palmas Arborea",
        "Pau",
        "Paulilatino",
        "Pompu",
        "Riola Sardo",
        "Ruinas",
        "Sagama",
        "Samugheo",
        "San Nicolò d'Arcidano",
        "Santa Giusta",
        "Santu Lussurgiu",
        "San Vero Milis",
        "Scano di Montiferro",
        "Sedilo",
        "Seneghe",
        "Senis",
        "Sennariolo",
        "Siamaggiore",
        "Siamanna",
        "Siapiccia",
        "Simala",
        "Simaxis",
        "Sini",
        "Siris",
        "Soddì",
        "Solarussa",
        "Sorradile",
        "Suni",
        "Tadasuni",
        "Terralba",
        "Tinnura",
        "Tramatza",
        "Tresnuraghes",
        "Ulà Tirso",
        "Uras",
        "Usellus",
        "Villanova Truschedu",
        "Villa Sant'Antonio",
        "Villaurbana",
        "Villa Verde",
        "Zeddiani",
        "Zerfaliu"
    ]
}
JSON, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new \LogicException('Unable to load Sardinian municipalities.', 0, $exception);
        }

        if (!is_array($locations)) {
            throw new \LogicException('Invalid Sardinian municipality list.');
        }

        /** @var array<string, list<string>> $locations */
        return self::$locations = $locations;
    }

    public static function isValid(string $province, string $city): bool
    {
        return in_array($city, self::all()[$province] ?? [], true);
    }

    /** @return array<string, array<string, string>> */
    public static function postalCodes(): array
    {
        if (self::$postalCodes !== null) {
            return self::$postalCodes;
        }

        try {
            $postalCodes = json_decode(<<<'JSON'
{
    "Città metropolitana di Cagliari": {
        "Armungia": "09040",
        "Assemini": "09032",
        "Ballao": "09040",
        "Barrali": "09040",
        "Burcei": "09040",
        "Cagliari": "09124",
        "Capoterra": "09012",
        "Castiadas": "09040",
        "Decimomannu": "09033",
        "Decimoputzu": "09010",
        "Dolianova": "09041",
        "Domus de Maria": "09010",
        "Donori": "09040",
        "Elmas": "09030",
        "Escalaplano": "08043",
        "Escolca": "08030",
        "Esterzili": "08030",
        "Genoni": "08030",
        "Gergei": "08030",
        "Gesico": "09040",
        "Goni": "09040",
        "Guamaggiore": "09040",
        "Guasila": "09040",
        "Isili": "08033",
        "Mandas": "09040",
        "Maracalagonis": "09040",
        "Monastir": "09023",
        "Monserrato": "09042",
        "Muravera": "09043",
        "Nuragus": "08030",
        "Nurallao": "08030",
        "Nuraminis": "09024",
        "Nurri": "08035",
        "Orroli": "08030",
        "Ortacesus": "09040",
        "Pimentel": "09020",
        "Pula": "09010",
        "Quartucciu": "09044",
        "Quartu Sant'Elena": "09045",
        "Sadali": "08030",
        "Samatzai": "09020",
        "San Basilio": "09040",
        "San Nicolò Gerrei": "09040",
        "San Sperate": "09026",
        "Sant'Andrea Frius": "09040",
        "San Vito": "09040",
        "Sarroch": "09018",
        "Selargius": "09047",
        "Selegas": "09040",
        "Senorbì": "09040",
        "Serdiana": "09040",
        "Serri": "08030",
        "Sestu": "09028",
        "Settimo San Pietro": "09040",
        "Siliqua": "09010",
        "Silius": "09040",
        "Sinnai": "09048",
        "Siurgus Donigala": "09040",
        "Soleminis": "09040",
        "Suelli": "09040",
        "Ussana": "09020",
        "Uta": "09010",
        "Vallermosa": "09010",
        "Villanova Tulo": "08030",
        "Villaputzu": "09040",
        "Villasalto": "09040",
        "Villa San Pietro": "09010",
        "Villasimius": "09049",
        "Villasor": "09034",
        "Villaspeciosa": "09010"
    },
    "Città metropolitana di Sassari": {
        "Alghero": "07041",
        "Anela": "07010",
        "Ardara": "07010",
        "Banari": "07040",
        "Benetutti": "07010",
        "Bessude": "07040",
        "Bonnanaro": "07043",
        "Bono": "07011",
        "Bonorva": "07012",
        "Borutta": "07040",
        "Bottidda": "07010",
        "Bultei": "07010",
        "Bulzi": "07030",
        "Burgos": "07010",
        "Cargeghe": "07030",
        "Castelsardo": "07031",
        "Cheremule": "07040",
        "Chiaramonti": "07030",
        "Codrongianos": "07040",
        "Cossoine": "07010",
        "Erula": "07030",
        "Esporlatu": "07010",
        "Florinas": "07030",
        "Giave": "07010",
        "Illorai": "07010",
        "Ittireddu": "07010",
        "Ittiri": "07044",
        "Laerru": "07030",
        "Mara": "07010",
        "Martis": "07030",
        "Monteleone Rocca Doria": "07010",
        "Mores": "07013",
        "Muros": "07030",
        "Nughedu San Nicolò": "07010",
        "Nule": "07010",
        "Nulvi": "07032",
        "Olmedo": "07040",
        "Osilo": "07033",
        "Ossi": "07045",
        "Ozieri": "07014",
        "Padria": "07015",
        "Pattada": "07016",
        "Perfugas": "07034",
        "Ploaghe": "07017",
        "Porto Torres": "07046",
        "Pozzomaggiore": "07018",
        "Putifigari": "07040",
        "Romana": "07010",
        "Santa Maria Coghinas": "07030",
        "Sassari": "07100",
        "Sedini": "07035",
        "Semestene": "07010",
        "Sennori": "07036",
        "Siligo": "07040",
        "Sorso": "07037",
        "Stintino": "07040",
        "Tergu": "07030",
        "Thiesi": "07047",
        "Tissi": "07040",
        "Torralba": "07048",
        "Tula": "07010",
        "Uri": "07040",
        "Usini": "07049",
        "Valledoria": "07039",
        "Viddalba": "07030",
        "Villanova Monteleone": "07019"
    },
    "Provincia dell'Ogliastra": {
        "Arzana": "08040",
        "Bari Sardo": "08042",
        "Baunei": "08040",
        "Cardedu": "08040",
        "Elini": "08040",
        "Gairo": "08040",
        "Girasole": "08040",
        "Ilbono": "08040",
        "Jerzu": "08044",
        "Lanusei": "08045",
        "Loceri": "08040",
        "Lotzorai": "08040",
        "Osini": "08040",
        "Perdasdefogu": "08046",
        "Seui": "08037",
        "Talana": "08040",
        "Tertenia": "08047",
        "Tortolì": "08048",
        "Triei": "08040",
        "Ulassai": "08040",
        "Urzulei": "08040",
        "Ussassai": "08040",
        "Villagrande Strisaili": "08049"
    },
    "Provincia della Gallura Nord-Est Sardegna": {
        "Aggius": "07020",
        "Aglientu": "07020",
        "Alà dei Sardi": "07020",
        "Arzachena": "07021",
        "Badesi": "07030",
        "Berchidda": "07022",
        "Bortigiadas": "07030",
        "Buddusò": "07020",
        "Budoni": "08020",
        "Calangianus": "07023",
        "Golfo Aranci": "07020",
        "La Maddalena": "07024",
        "Loiri Porto San Paolo": "07020",
        "Luogosanto": "07020",
        "Luras": "07025",
        "Monti": "07020",
        "Olbia": "07026",
        "Oschiri": "07027",
        "Padru": "07020",
        "Palau": "07020",
        "Sant'Antonio di Gallura": "07030",
        "Santa Teresa Gallura": "07028",
        "San Teodoro": "08020",
        "Telti": "07020",
        "Tempio Pausania": "07029",
        "Trinità d'Agultu e Vignola": "07038"
    },
    "Provincia del Medio Campidano": {
        "Arbus": "09031",
        "Barumini": "09021",
        "Collinas": "09020",
        "Furtei": "09040",
        "Genuri": "09020",
        "Gesturi": "09020",
        "Gonnosfanadiga": "09035",
        "Guspini": "09036",
        "Las Plassas": "09020",
        "Lunamatrona": "09022",
        "Pabillonis": "09030",
        "Pauli Arbarei": "09020",
        "Samassi": "09030",
        "San Gavino Monreale": "09037",
        "Sanluri": "09025",
        "Sardara": "09030",
        "Segariu": "09040",
        "Serramanna": "09038",
        "Serrenti": "09027",
        "Setzu": "09029",
        "Siddi": "09020",
        "Tuili": "09029",
        "Turri": "09020",
        "Ussaramanna": "09020",
        "Villacidro": "09039",
        "Villamar": "09020",
        "Villanovaforru": "09020",
        "Villanovafranca": "09020"
    },
    "Provincia del Sulcis Iglesiente": {
        "Buggerru": "09010",
        "Calasetta": "09011",
        "Carbonia": "09013",
        "Carloforte": "09014",
        "Domusnovas": "09015",
        "Fluminimaggiore": "09010",
        "Giba": "09010",
        "Gonnesa": "09010",
        "Iglesias": "09016",
        "Masainas": "09010",
        "Musei": "09010",
        "Narcao": "09010",
        "Nuxis": "09010",
        "Perdaxius": "09010",
        "Piscinas": "09010",
        "Portoscuso": "09010",
        "San Giovanni Suergiu": "09010",
        "Sant'Anna Arresi": "09010",
        "Sant'Antioco": "09017",
        "Santadi": "09010",
        "Teulada": "09019",
        "Tratalias": "09010",
        "Villamassargia": "09010",
        "Villaperuccio": "09010"
    },
    "Provincia di Nuoro": {
        "Aritzo": "08031",
        "Atzara": "08030",
        "Austis": "08030",
        "Belvì": "08030",
        "Birori": "08010",
        "Bitti": "08021",
        "Bolotana": "08011",
        "Borore": "08016",
        "Bortigali": "08012",
        "Desulo": "08032",
        "Dorgali": "08022",
        "Dualchi": "08010",
        "Fonni": "08023",
        "Gadoni": "08030",
        "Galtellì": "08020",
        "Gavoi": "08020",
        "Irgoli": "08020",
        "Lei": "08010",
        "Loculi": "08020",
        "Lodine": "08020",
        "Lodè": "08020",
        "Lula": "08020",
        "Macomer": "08015",
        "Mamoiada": "08024",
        "Meana Sardo": "08030",
        "Noragugume": "08010",
        "Nuoro": "08100",
        "Oliena": "08025",
        "Ollolai": "08020",
        "Olzai": "08020",
        "Onanì": "08020",
        "Onifai": "08020",
        "Oniferi": "08020",
        "Orani": "08026",
        "Orgosolo": "08027",
        "Orosei": "08028",
        "Orotelli": "08020",
        "Ortueri": "08036",
        "Orune": "08020",
        "Osidda": "08020",
        "Ottana": "08020",
        "Ovodda": "08020",
        "Posada": "08020",
        "Sarule": "08020",
        "Seulo": "08030",
        "Silanus": "08017",
        "Sindia": "08018",
        "Siniscola": "08029",
        "Sorgono": "08038",
        "Teti": "08030",
        "Tiana": "08020",
        "Tonara": "08039",
        "Torpè": "08020"
    },
    "Provincia di Oristano": {
        "Abbasanta": "09071",
        "Aidomaggiore": "09070",
        "Albagiara": "09090",
        "Ales": "09091",
        "Allai": "09080",
        "Arborea": "09092",
        "Ardauli": "09081",
        "Assolo": "09080",
        "Asuni": "09080",
        "Baradili": "09090",
        "Baratili San Pietro": "09070",
        "Baressa": "09090",
        "Bauladu": "09070",
        "Bidonì": "09080",
        "Bonarcado": "09070",
        "Boroneddu": "09080",
        "Bosa": "08013",
        "Busachi": "09082",
        "Cabras": "09072",
        "Cuglieri": "09073",
        "Curcuris": "09090",
        "Flussio": "08010",
        "Fordongianus": "09083",
        "Ghilarza": "09074",
        "Gonnoscodina": "09090",
        "Gonnosnò": "09090",
        "Gonnostramatza": "09093",
        "Laconi": "08034",
        "Magomadas": "08010",
        "Marrubiu": "09094",
        "Masullas": "09090",
        "Milis": "09070",
        "Modolo": "08019",
        "Mogorella": "09080",
        "Mogoro": "09095",
        "Montresta": "08010",
        "Morgongiori": "09090",
        "Narbolia": "09070",
        "Neoneli": "09080",
        "Norbello": "09070",
        "Nughedu Santa Vittoria": "09080",
        "Nurachi": "09070",
        "Nureci": "09080",
        "Ollastra": "09088",
        "Oristano": "09170",
        "Palmas Arborea": "09090",
        "Pau": "09090",
        "Paulilatino": "09070",
        "Pompu": "09093",
        "Riola Sardo": "09070",
        "Ruinas": "09085",
        "Sagama": "08010",
        "Samugheo": "09086",
        "San Nicolò d'Arcidano": "09097",
        "Santa Giusta": "09096",
        "Santu Lussurgiu": "09075",
        "San Vero Milis": "09070",
        "Scano di Montiferro": "09078",
        "Sedilo": "09076",
        "Seneghe": "09070",
        "Senis": "09080",
        "Sennariolo": "09078",
        "Siamaggiore": "09070",
        "Siamanna": "09080",
        "Siapiccia": "09080",
        "Simala": "09090",
        "Simaxis": "09088",
        "Sini": "09090",
        "Siris": "09090",
        "Soddì": "09080",
        "Solarussa": "09077",
        "Sorradile": "09080",
        "Suni": "08010",
        "Tadasuni": "09080",
        "Terralba": "09098",
        "Tinnura": "08010",
        "Tramatza": "09070",
        "Tresnuraghes": "09079",
        "Ulà Tirso": "09080",
        "Uras": "09099",
        "Usellus": "09090",
        "Villanova Truschedu": "09084",
        "Villa Sant'Antonio": "09080",
        "Villaurbana": "09080",
        "Villa Verde": "09090",
        "Zeddiani": "09070",
        "Zerfaliu": "09070"
    }
}
JSON, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new \LogicException('Unable to load Sardinian postal codes.', 0, $exception);
        }

        if (!is_array($postalCodes)) {
            throw new \LogicException('Invalid Sardinian postal-code list.');
        }

        /** @var array<string, array<string, string>> $postalCodes */
        return self::$postalCodes = $postalCodes;
    }

    public static function postalCode(string $province, string $city): ?string
    {
        return self::postalCodes()[$province][$city] ?? null;
    }

    /** @return array{province: string, city: string}|null */
    public static function locationForPostalCode(string $postalCode): ?array
    {
        $matches = [];
        foreach (self::postalCodes() as $province => $cities) {
            foreach ($cities as $city => $candidate) {
                if ($candidate === $postalCode) {
                    $matches[] = ['province' => $province, 'city' => $city];
                }
            }
        }

        return count($matches) === 1 ? $matches[0] : null;
    }

    /** @return list<string> */
    public static function provinces(): array
    {
        return array_keys(self::all());
    }
}
